name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Verify PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Clean lib
        run: rm -Rf lib

      - name: Build Project
        run: npm run ci
